@extends('layout')
@section('conteudo')
   @include('agendamento')
   @include('concessionaria')
   @include('concesusuario')
   @include('equipe')
   @include('especialidade')
   @include('funcionario')
   @include('modelo')
   @include('ordensdeservico')
   @include('statusos')
   @include('tipo')
   @include('programacao')
   @include('apontamento')
   @include('excecaocarga')
   @include('intervaloagenda')
   @include('logcarga')
   @include('os')
   @include('oslog')
   @include('paineisagenda')
   @include('primas')
   @include('statusagenda')
   @include('telausuario')
   @include('tipoagenda')
   @include('usuario')


@endsection
